apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2-frontend
  template:
    metadata:
      labels:
        app: service2-frontend
    spec:
      containers:
        - name: service2-frontend
          image: service2-frontend-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service2-frontend-service
spec:
  type: NodePort
  selector:
    app: service2-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004 