apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2-backend
  template:
    metadata:
      labels:
        app: service2-backend
    spec:
      containers:
        - name: service2-backend
          image: service2-backend-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: service2-backend-service
spec:
  type: NodePort
  selector:
    app: service2-backend
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30003 