apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1-frontend
  template:
    metadata:
      labels:
        app: service1-frontend
    spec:
      containers:
        - name: service1-frontend
          image: your-dockerhub-username/service1-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service1-frontend-service
spec:
  type: NodePort
  selector:
    app: service1-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
