apiVersion: apps/v1
kind: Deployment
metadata:
  name: service4-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service4-backend
  template:
    metadata:
      labels:
        app: service4-backend
    spec:
      containers:
        - name: service4-backend
          image: service4-backend-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5004
---
apiVersion: v1
kind: Service
metadata:
  name: service4-backend-service
spec:
  type: NodePort
  selector:
    app: service4-backend
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
      nodePort: 30007 