apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service3-backend
  template:
    metadata:
      labels:
        app: service3-backend
    spec:
      containers:
        - name: service3-backend
          image: service3-backend-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: service3-backend-service
spec:
  type: NodePort
  selector:
    app: service3-backend
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
      nodePort: 30005 