apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1-backend
  template:
    metadata:
      labels:
        app: service1-backend
    spec:
      containers:
        - name: service1-backend
          image: your-dockerhub-username/service1-backend:latest
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: service1-backend-service
spec:
  type: NodePort
  selector:
    app: service1-backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30002
