name: CI/CD Pipeline for Service1

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      IMAGE_PREFIX: ${{ secrets.DOCKER_USERNAME }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push service1-backend
      run: |
        docker build -t $REGISTRY/$IMAGE_PREFIX/service1-backend:latest ./backend/service1-backend
        docker push $REGISTRY/$IMAGE_PREFIX/service1-backend:latest

    - name: Build & Push service1-frontend
      run: |
        docker build -t $REGISTRY/$IMAGE_PREFIX/service1-frontend:latest ./frontend/service1-frontend
        docker push $REGISTRY/$IMAGE_PREFIX/service1-frontend:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.32.2'

    - name: Deploy to Kubernetes
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        kubectl apply --validate=false -f k8s/service1-backend-deployment.yaml
        kubectl apply --validate=false -f k8s/service1-frontend-deployment.yaml
